### ISSUE TITLE
Broad - Jade

### ISSUE THREAD

**Issue by amarjandu** [ucsc-cgp/team-redwood#16]
- [x] Setup Jade System
- [x] Feedback

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/RWD-17)
┆Project Name: Team Redwood
┆Issue Number: RWD-17

**Comment by amarjandu** [comment]
https://drive.google.com/open?id=15ygJEaRTar0yinysuLQyQnpzaGQMplYc

**Comment by kozbo** [comment]
@amarjandu can you create a Goggle doc link so that I can comment directly in the doc? (post here)

**Comment by amarjandu** [comment]
Updated with feedback.

https://docs.google.com/document/d/1JybliLyOO8KvxftCytBxcwUWgUHBxQUQQB26la-rnzg/edit?usp=sharing

**Comment by kozbo** [comment]
@xbrianh this looks done to me. If you agree we should share it with the Broad team. 
Thanks @amarjandu !
