### ISSUE TITLE
Resource Tagging RFC

### ISSUE THREAD

**Issue by amarjandu** [ucsc-cgp/team-redwood#17]
- [x] usher RFC along
- [ ] update on-boarding documents with required tagging

Build out Cost Explorer Examples? --Within scope?

see https://github.com/HumanCellAtlas/data-store/issues/1997 for additional information.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/RWD-18)
┆Project Name: Team Redwood
┆Issue Number: RWD-18

**Comment by amarjandu** [comment]
RFC moved to oversight review

**Comment by kozbo** [comment]
The RFC has been merged. Make a new ticket for any residuals and close this one.
