### ISSUE TITLE
DRS Prototype

### ISSUE THREAD

**Issue by david4096** [ucsc-cgp/team-redwood#5]
Demonstrate a DRS aligned service that can manage, sign, and authenticate requests for data from multiple cloud storage environments.

This should be implementable completely in Google Cloud infrastructure for storing controlled access data.

https://docs.google.com/presentation/d/1OKSsF5_5X-RbFYPzYMKrXUZQf-SSwvDDK93QjzVHgJI/edit

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/RWD-14)
┆Project Name: Team Redwood
┆Issue Number: RWD-14

**Comment by kozbo** [comment]
This was  completed via the demo that David produced, closing
